### ISSUE TITLE
`g2tmpl@1.10.2` build errors on spack clang container - `pic` variant?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#525] opened 2023-03-27 13:54 UTC
**Describe the bug**
I tried to update `g2tmpl` in the spack containers from 1.10.0 to 1.10.2 and got this error for the `clang` container. That error doesn't happen with 1.10.0. And it doesn't occur with `gnu`, nor with Intel, for 1.10.2.
```
[+] /opt/software/linux-ubuntu20.04-x86_64/clang-10.0.0/eigen-3.4.0-mv4smxvjf5pdoyn2rhovfczo6wh3roq2
==> Installing g2tmpl-1.10.2-u47d2hx6ihdzdow4cbgk6qqgtjl4ryjo
==> g2tmpl exists in binary cache but with different hash
==> No binary for g2tmpl-1.10.2-u47d2hx6ihdzdow4cbgk6qqgtjl4ryjo found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/40/4063361369f3691f75288c801fa9d1a2414908b7d6c07bbf69d4165802e2a7fc.tar.gz
==> No patches needed for g2tmpl
==> g2tmpl: Executing phase: 'cmake'
==> g2tmpl: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j2'

4 errors found in build log:
     55    [ 87%] Building Fortran object src/CMakeFiles/sort_params_grib2_tbl.
           dir/sort_params_grib2_tbl.f90.o
     56    cd /tmp/root/spack-stage/spack-stage-g2tmpl-1.10.2-u47d2hx6ihdzdow4c
           bgk6qqgtjl4ryjo/spack-build-u47d2hx/src && /opt/spack/lib/spack/env/
           clang/gfortran -DLINUX -DUNDERSCORE -I/tmp/root/spack-stage/spack-st
           age-g2tmpl-1.10.2-u47d2hx6ihdzdow4cbgk6qqgtjl4ryjo/spack-build-u47d2
           hx/src/include -g -fbacktrace -funroll-loops  -O2 -g -DNDEBUG -c /tm
           p/root/spack-stage/spack-stage-g2tmpl-1.10.2-u47d2hx6ihdzdow4cbgk6qq
           gtjl4ryjo/spack-src/src/sort_params_grib2_tbl.f90 -o CMakeFiles/sort
           _params_grib2_tbl.dir/sort_params_grib2_tbl.f90.o
     57    [100%] Linking Fortran executable sort_params_grib2_tbl
     58    cd /tmp/root/spack-stage/spack-stage-g2tmpl-1.10.2-u47d2hx6ihdzdow4c
           bgk6qqgtjl4ryjo/spack-build-u47d2hx/src && /opt/software/linux-ubunt
           u20.04-x86_64/clang-10.0.0/cmake-3.23.1-q54sfz74mb5v6lrfo5cqnfo27efd
           xpvg/bin/cmake -E cmake_link_script CMakeFiles/sort_params_grib2_tbl
           .dir/link.txt --verbose=1
     59    /opt/spack/lib/spack/env/clang/gfortran -g -fbacktrace -funroll-loop
           s  -O2 -g -DNDEBUG CMakeFiles/sort_params_grib2_tbl.dir/sort_params_
           grib2_tbl.f90.o -o sort_params_grib2_tbl   -L/usr/lib/llvm-10/lib  l
           ibg2tmpl.a
     60    /usr/bin/ld: libg2tmpl.a(process_4dot2.c.o): relocation R_X86_64_32
           against `.rodata.str1.1' can not be used when making a PIE object; r
           ecompile with -fPIE
  >> 61    collect2: error: ld returned 1 exit status
  >> 62    make[2]: *** [src/CMakeFiles/sort_params_grib2_tbl.dir/build.make:10
           0: src/sort_params_grib2_tbl] Error 1
     63    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-g2tmpl
           -1.10.2-u47d2hx6ihdzdow4cbgk6qqgtjl4ryjo/spack-build-u47d2hx'
  >> 64    make[1]: *** [CMakeFiles/Makefile2:129: src/CMakeFiles/sort_params_g
           rib2_tbl.dir/all] Error 2
     65    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-g2tmpl
           -1.10.2-u47d2hx6ihdzdow4cbgk6qqgtjl4ryjo/spack-build-u47d2hx'
  >> 66    make: *** [Makefile:139: all] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-g2tmpl-1.10.2-u47d2hx6ihdzdow4cbgk6qqgtjl4ryjo/spack-build-out.txt

==> Warning: Skipping external package: git@2.25.1%clang@10.0.0+man+nls+perl+subtree~svn~tcltk build_system=autotools arch=linux-ubuntu20.04-x86_64/3y4ddgt
==> Warning: Skipping external package: mpich@4.0.2%clang@10.0.0~argobots~cuda+fortran~hwloc+hydra+libxml2+pci~rocm+romio~slurm+two_level_namespace~vci~verbs+wrapperrpath build_system=autotools datatype-engine=auto device=ch4 netmod=ofi patches=d4c0e99 pmi=pmi arch=linux-ubuntu20.04-x86_64/a2htl6v
==> Warning: Skipping external package: wget@1.20.3%clang@10.0.0~libpsl~pcre~python+zlib build_system=autotools ssl=openssl arch=linux-ubuntu20.04-x86_64/2ebl2wd
==> Warning: Skipping external package: git-lfs@2.9.2%clang@10.0.0 build_system=makefile arch=linux-ubuntu20.04-x86_64/xirczbu
==> Warning: Skipping external package: qt@5.12.8%clang@10.0.0~dbus~debug~doc~examples~framework~gtk+gui~opengl~phonon+shared+sql+ssl+tools~webkit build_system=generic patches=51aeba5,7f34d48,c52f72d arch=linux-ubuntu20.04-x86_64/zfym43m
==> Warning: Skipping external package: mysql@8.0.32%clang@10.0.0~client_only~ipo build_system=cmake build_type=RelWithDebInfo cxxstd=14 arch=linux-ubuntu20.04-x86_64/5sbij7x
==> Error: Terminating after first install failure: ProcessError: Command exited with status 2:
    'make' '-j2'
```
Looking at https://github.com/NOAA-EMC/spack/blob/425f8f2dd8c00bcf21845ff225ceb256a6677fd7/var/spack/repos/builtin/packages/g2tmpl/package.py I don't see a `pic` variant, which is usually used to fix these type of linker problems.

**To Reproduce**
Follow the instructions `configs/containers/README.md` to build the containers and watch in awe.

**Expected behavior**
`g2tmpl@10.0.2` builds w/o errors.

**System:**
Ubuntu 20.04 running docker to build spack JEDI containers as per instructions in `configs/containers/README.md`.

**Additional context**
n/a

**Comment by climbfuji** [comment] 2023-09-15 14:52
This problem solved itself, presumably by an update from mainline spack.

**Comment by climbfuji** [comment] 2023-09-15 17:07
Reopening, this is still an issue (I mistakenly checked the gnu container, not the clang container).

**Comment by climbfuji** [comment] 2023-09-29 14:02
@AlexanderRichert-NOAA Do you think you can help with that? Do you have a setup of Linux with `clang`?

**Comment by AlexanderRichert-NOAA** [comment] 2023-09-29 18:37
I don't but I can take a look.

**Comment by AlexanderRichert-NOAA** [comment] 2023-10-02 23:32
I can reproduce the issue on Ubuntu 20.04 with clang 10 and gfortran 9. It looks like it's a mismatch in default settings between clang and gfortran. I can add a PIC variant, and it will also work if you add `cflags=-fPIE` or `cflags=-fPIC`. If it doesn't happen in any other packages, we could also put something in the cmake that requires fPIC if we're using clang and gfortran together (although I wasn't able to reproduce the issue on my personal machine, it might be due to RedHat vs. Ubuntu differences in clang default settings).

**Comment by AlexanderRichert-NOAA** [comment] 2023-10-02 23:46
FWIW this can also be resolved with `fflags=-no-pie`. Unfortunately setting CMAKE_POSITION_INDEPENDENT_CODE=OFF does not seem to override the gfortran default of enabling it.

**Comment by climbfuji** [comment] 2023-10-03 02:15
Thanks @AlexanderRichert-NOAA ! Since this is not reproducible on every machine, I think making this a variant in the container yaml and adding an entry in the known issues FAQ is sufficient. I can do that if you like.

**Comment by AlexanderRichert-NOAA** [comment] 2023-10-03 16:01
Sounds good

**Closed as completed** 2023-10-06 16:47 UTC
Labels: bug, INFRA
