### ISSUE TITLE
[INSTALL] intel-openmpi on nautilus

### ISSUE THREAD

**Issue by areinecke** [JCSDA/spack-stack#633] opened 2023-06-20 17:27 UTC
Please add intel-openmpi stack on nautilus.  Using intelmpi-intel on AMD Epyc Rome infiniband machines produces a deadlock with all2all type communications (JCSDA-internal/oops#2191).  The problem has also been reported with ESMF.  Using openmpi instead of intelmpi fixes the problem with ESMF.

**Which software in the stack would you like installed?**
Please provide the name of the software you would like installed on the HPCs.  Ensure the software exists in the list of supported software.  If new software needs to be added to the stack, use the [add_package_request.md](./add_package_request.md) template.

**What is the version/tag of the software?**
Please provide the version/tag of the software to be installed.

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.

**Which machines would you like to have the software installed?**
See currently managed HPC machines.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by sking112** [comment] 2023-06-21 16:34
With respect to the jedi-neptune-env we are using CRTM 2.4.0. This seems to conflict with the crtm/v2.4.1-jedi module in the jedi-base-env/1.0.0 module.

**Comment by climbfuji** [comment] 2023-06-21 16:49
@sking112 Can you please specify exactly which version you are using? There are many different versions: 2.4.0 EMC, 2.4-jedi.1, 2.4-jedi.2.

**Comment by sking112** [comment] 2023-06-21 23:49
@climbfuji we're using a checkout #cfa484491 in our bundle. Looks like its from Feb 2021. I can switch us to one of those versions but I don't know what the difference is between them.

**Comment by climbfuji** [comment] 2023-06-22 22:19
@sking112 I ran a view diffs of that hash with tags in the CRTM repo. I also checked with @BenjaminTJohnson. Your hash is very close to the 2.4.0 tag (note that this tag has no suffix, i.e. it is not the EMC version and it is not the JEDI version). We don't have that particular tag in spack-stack yet.

We have three options:
- Add the 2.4.0 tag to spack and label it such that it is distinguishable from the existing 2.4.0 version in spack (which is the EMC) version, and make it default in `jedi-neptune-env`
- If 2.4.0 doesn't work, create a "version" for hash #cfa484491 in spack and make that default in `jedi-neptune-env`
- Remove crtm from the spack-stack module environment altogether for `jedi-neptune-env` and let you build whatever you want yourself in the bundle

**Comment by sking112** [comment] 2023-06-22 22:32
@climbfuji would it be easy to remove the crtm module for now?

**Comment by climbfuji** [comment] 2023-06-23 03:52
> @climbfuji would it be easy to remove the crtm module for now?

It requires a bit of a workaround, but it can be done. We'll need to make changes to `jedi-base-env` and a few other places. The easiest solution would be if we could simply unload the crtm module, so let me try to reproduce what is giving you such a hard time.

**Comment by climbfuji** [comment] 2023-06-23 14:45
@areinecke Quick update. I am hitting a compilation error with Intel + OpenMPI for parallel-netcdf (which is required for parallelio, esmf, ...). I'll need some time to debug this:
```
7 errors found in build log:
     722    mv -f .deps/ncmpiFile.Tpo .deps/ncmpiFile.Plo
     723    mv -f .deps/ncmpiVlenType.Tpo .deps/ncmpiVlenType.Plo
     724    mv -f .deps/ncmpiVarAtt.Tpo .deps/ncmpiVarAtt.Plo
     725    libtool: compile:  /opt/scyld/openmpi/4.1.4/intel/bin/mpic++ -DHAVE_CONFIG_H -I. -I../../../src/include -I../../../src/include -fPIC -MT ncmpiVar.lo -MD -MP -MF .deps/ncmpiVar.Tpo -c ncmpiVar.cpp -o
            ncmpiVar.o >/dev/null 2>&1
     726    mv -f .deps/ncmpiVar.Tpo .deps/ncmpiVar.Plo
     727    /bin/sh ../../../libtool  --tag=CXX   --mode=link /opt/scyld/openmpi/4.1.4/intel/bin/mpic++  -fPIC   -o libcxx.la  ncmpi_notyet.lo ncmpiCheck.lo ncmpiType.lo ncmpiAtt.lo ncmpiEnumType.lo ncmpiGroupAt
            t.lo ncmpiGroup.lo ncmpiByte.lo ncmpiChar.lo ncmpiCompoundType.lo ncmpiDouble.lo ncmpiFloat.lo ncmpiInt.lo ncmpiInt64.lo ncmpiOpaqueType.lo ncmpiShort.lo ncmpiUbyte.lo ncmpiUint.lo ncmpiUint64.lo ncm
            piUshort.lo ncmpiException.lo ncmpiDim.lo ncmpiFile.lo ncmpiVarAtt.lo ncmpiVar.lo ncmpiVlenType.lo
  >> 728    /usr/bin/grep: /opt/scyld/pbs/lib/libpbs.la: No such file or directory
  >> 729    /usr/bin/sed: can't read /opt/scyld/pbs/lib/libpbs.la: No such file or directory
     730    libtool:   error: '/opt/scyld/pbs/lib/libpbs.la' is not a valid libtool archive
  >> 731    make[4]: *** [Makefile:566: libcxx.la] Error 1
     732    make[4]: Leaving directory '/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/cache/build_stage/heinzell/spack-stage-parallel-netcdf-1.12.2-trtldc5y2ygbiabr7c4loidzymk4dlmv/spack-src/src/binding/
            cxx'
  >> 733    make[3]: *** [Makefile:520: all] Error 2
     734    make[3]: Leaving directory '/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/cache/build_stage/heinzell/spack-stage-parallel-netcdf-1.12.2-trtldc5y2ygbiabr7c4loidzymk4dlmv/spack-src/src/binding/
            cxx'
  >> 735    make[2]: *** [Makefile:474: all-recursive] Error 1
     736    make[2]: Leaving directory '/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/cache/build_stage/heinzell/spack-stage-parallel-netcdf-1.12.2-trtldc5y2ygbiabr7c4loidzymk4dlmv/spack-src/src/binding'
  >> 737    make[1]: *** [Makefile:476: all-recursive] Error 1
     738    make[1]: Leaving directory '/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/cache/build_stage/heinzell/spack-stage-parallel-netcdf-1.12.2-trtldc5y2ygbiabr7c4loidzymk4dlmv/spack-src/src'
  >> 739    make: *** [Makefile:533: all-recursive] Error 1
```

**Comment by climbfuji** [comment] 2023-06-23 17:56
@areinecke I found many more openmpi installations with modules. I am going to try another openmpi first (`penguin/openmpi/4.1.5rc2/intel`) before I spend time to debug this.

**Comment by climbfuji** [comment] 2023-06-28 02:10
@sking112 You mentioned that you can't unload crtm without unloading all the other modules on nautilus (which uses tcl/tk environment modules). Have you tried `module unload --force crtm`? This works for me on Red Hat with tcl/tk modules.

As you've seen we made a change in spack-stack develop to not load crtm by default (we still want to build it, but not load the module by default), which will be in spack-stack-1.5.0 in a few months time. While we can do another intermediate spack-stack install on Nautilus, the easiest would be if `--force` worked.

**Comment by climbfuji** [comment] 2023-07-03 15:35
@areinecke @sking112 This is now ready for testing, with MKL. Yet another directory, because it's now based on the latest spack-stack develop code instead of the 1.4.0 release.

From the updated documentation:
```
With Intel, the following is required for building new spack environments and for using spack to build and run software.

.. code-block:: console

   umask 0022
   module purge

   module load slurm
   module load intel/compiler/2022.0.2
   module load penguin/openmpi/4.1.5rc2/intel

   module use /p/app/projects/NEPTUNE/spack-stack/modulefiles
   module load ecflow/5.8.4
   module load mysql/8.0.31

For ``spack-stack-1.4.0`` with Intel, load the following modules after loading the above modules.

.. code-block:: console

   module use /p/app/projects/NEPTUNE/spack-stack/spack-stack-dev-20230628/envs/unified-env/install/modulefiles/Core
   module load stack-intel/2021.5.0
   module load stack-openmpi/4.1.5rc2
   module load stack-python/3.10.8
```

I built jedi-bundle on Nautilus and ran the ctests, and all of those expected to pass did pass.

**Closed as completed** 2023-07-06 21:24 UTC
Labels: INFRA
