### ISSUE TITLE
netcdf-c and netcdf-fortran can be updated, with special measures to enable zstandard compression

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#295] opened 2022-08-02 17:57 UTC
netcdf-c-4.9.0 and netcdf-fortran-4.6.0 are out! ;-)

In order for zstandard compression to work, the zstandard library must be installed before netcdf-c is built.

Also the configure option --with-plugin-dir=/some/dir.

Then the environment variable HDF5_PLUGIN_PATH must be set to /some/dir, for netcdf-fortran and every application that wants to use zstandard.

That is, if some rando netCDF application calls nc_def_var_zstandard() (or its fortran wrappers), the must have the HDF5_PLUGIN_PATH environment variable set correctly. or when they run that code they will get a "filter not found" error.

So this may present a challenge for spack. @kgerheiser you are now much more familar with spack than I am - what do you think is the best way to do this?

**Comment by kgerheiser** [comment] 2022-08-02 18:09
This is all pretty easy with Spack. 

* `zstd` is already a package
* Add `--with-plugin-dir` to `netcdf-c` in `configure_args` (with a `+plugins` variant or would it be `+zstd`?)
* `HDF5_PLUGIN_PATH` can be set with `setup_run_environment()` method (in `netcdf-c`?). 

I'm a little hazy where `zstd` is actually used here. Would you add a `depends_on(zstd)` to the HDF5 or NetCDF package? And it would presumably  be behind a variant like `+zstd`?

**Comment by edwardhartnett** [comment] 2022-08-02 19:03
zstd is used by HDF5.

**Comment by kgerheiser** [comment] 2022-08-02 19:06
Is there some sort of option to pass to `configure` to use zstd in NetCDF?

**Comment by edwardhartnett** [comment] 2022-08-02 19:26
If it is found, and --with-plugin-dir is used, then zstandard will be enabled.

It's included in the list of features summarized at the end of configure, and in netcdf_meta.h, so you can check to ensure that zstandard is built, and plugins are installed.

**Comment by kgerheiser** [comment] 2022-08-02 20:23
How does NetCDF detect zstd? I guess there needs to be a `-I${ZSTD_INC} -L${ZSTD_LIBDIR} -lzstd` sort of thing added to the configure flags?

**Comment by edwardhartnett** [comment] 2022-08-03 13:01
Yes the include and library paths need to be found. No need to set -lzstd, the configure does that.

If you install zstandard in the usual place on linux systems (sudo apt-get install zlib-dev) then everything is found without further effort.

**Comment by mathomp4** [comment] 2022-08-04 16:14
One note, I might also suggest adding `--with-hdf5-plugin-path` to NCO's build as well. Per [Charlie Zender on the mailing list](https://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2022/msg00041.html) it's not *required* but it might make things more robust. (Seems to be true in my testing.)

I suppose the question is if the setting/appending of the `HDF5_PLUGIN_PATH` environment variable in the netcdf-c package would be tripped by a `spack load nco`. Probably?

**Comment by mathomp4** [comment] 2022-08-04 16:24
Also, and maybe @edwardhartnett would know the answer to this, is it necessary or good to set `H5_DEFAULT_PLUGINDIR` (or the equivalent `--with-default-plugindir`) when building HDF5 to match the value provided to netcdf-c in `--with-plugin-dir`? 

I did that in my Baselibs testing only because, well, some Google search about HDF5 plugins talked about it most likely and my fear was based on the fact that HDF5 seems to default to `/usr/local`:

```
    H5_DEFAULT_PLUGINDIR    "/usr/local/hdf5/lib/plugin"
```

But I suppose if netCDF is the one installing to that path, then all netcdf based programs would be fine. It might only be HDF5 programs that would need to know...and even then the `HDF5_PLUGIN_PATH` might be enough!

**Comment by kgerheiser** [comment] 2022-08-04 18:09
> I suppose the question is if the setting/appending of the HDF5_PLUGIN_PATH environment variable in the netcdf-c package would be tripped by a spack load nco. Probably?

This is a good point. If using modules with `autload: direct`, then having the `netcdf-c` module loaded is enough because NCO will load NetCDF, but I don't think it'll populate a `spack load nco` because the default `depends_on()` is `(build, link)` (not run). So, the variable should be set in `setup_dependent_run_environment()` so that it sets it for dependencies as well.

**Comment by kgerheiser** [comment] 2022-08-04 18:19
I can confirm that `spack load nco` correctly populates `HDF5_PLUGIN_PATH` from `netcdf-c` with just `setup_run_environment`

**Comment by kgerheiser** [comment] 2022-08-04 18:33
> Also, and maybe @edwardhartnett would know the answer to this, is it necessary or good to set H5_DEFAULT_PLUGINDIR (or the equivalent --with-default-plugindir) when building HDF5 to match the value provided to netcdf-c in --with-plugin-dir?

Also a good question. I think it's a matter of taste. You could put all your plugins in the same location, or in separate places (and append to `HDF5_PLUGIN_PATH`). In Spack I think it's good to have the plugins that NetCDF installs in the NetCDF prefix, but in Baselibs it seems reasonable to point them to the same location. By setting `H5_DEFAULT_PLUGINDIR` you don't have to explictly set `HDF5_PLUGIN_PATH` as an environment variable, but Spack handles this automatically.

**Comment by climbfuji** [comment] 2022-08-24 01:57
Note. The corresponding PR for the authoritative spack repo is https://github.com/spack/spack/pull/31953. After that PR gets merged, we should cherry-pick those changes and bring them over (or update to the head of develop). This can be done as part of https://github.com/NOAA-EMC/spack/pull/146.

**Closed as completed** 2022-11-22 14:48 UTC
