### ISSUE TITLE
Use "require" in common/packages.yaml?

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#883] opened 2023-11-20 18:55 UTC
Given that spack supports hard requirements for package versions and variants, as opposed to the 'version:' and 'variants:' sections which only configure those selections as soft preferences, would it make sense to update everything in common/packages.yaml to use 'require:'? This would help prevent unwanted config changes, and could maybe even prevent some of the duplicate package issues we've run into.

**Comment by climbfuji** [comment] 2023-11-21 16:08
Yes. There's a related issue in spack-stack on cleaning up configs/common/packages.yaml - see https://github.com/JCSDA/spack-stack/issues/758

**Comment by climbfuji** [comment] 2023-12-19 22:18
@AlexanderRichert-NOAA We've started using `require` in places in `configs/common/packages.yaml`. It's not applicable everywhere, but we should continue this effort on develop and consider the changes we've made for release/1.6.0 as complete  (that is, keep issue open and as "in progress" for project "release/1.7.0", but mark as "done" for project "release/1.6.0"). Ok with you?

**Comment by AlexanderRichert-NOAA** [comment] 2023-12-19 23:04
Yep sounds good, thanks!

**Comment by climbfuji** [comment] 2024-05-13 15:25
This is a duplicate of another issue that covers cleaning up configs/common/packages.yaml.

**Closed as not planned by climbfuji** 2024-05-13 15:25 UTC
Labels: INFRA, NOAA-EMC
