### ISSUE TITLE
Create a GSI/global-workflow addon environment

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#864] opened 2023-11-06 16:06 UTC
**Is your feature request related to a problem? Please describe.**
The GSI, GSI_Utils, GSI_Monitor, GFS_Utils, EMC_Verif-Global, and global-wokflow repositories are all using older versions of BUFR (11.7.0) and the EMC_Verif-Global and global-workflow repositories are also using older versions of MET and METplus (9.1.3 and 3.1.1, respectively).

**Describe the solution you'd like**
An environment has been created under the spack-stack/1.5.1 installations on Hera, Orion, Jet, Gaea, and S4 and an environment template should be created to capture these required libraries.  Additionally, it would be ideal to have this as a downstream environment to the unified-env.

**Additional context**
The BUFR library is being investigated for a slowdown between versions 11.7.0 and 12.0.0 to see what optimizations can be made.  When completed, the GSI* repositories can be upgraded to use the newest BUFR tag.

The EMC_Verif-Global repository relies on the older versions of MET and METplus and will not go through an upgrade to newer versions.  Instead, the EVS repository is being developed as a replacement (production handoff date 11/19; R&D TBD).  Until then, it is necessary to have these older versions to run the package.

**Comment by DavidHuber-NOAA** [comment] 2023-12-05 13:57
I have created a baseline addon template for the GSI, but am having trouble getting MET/9.1.3 to compile.  The branch is available [here](https://github.com/DavidHuber-NOAA/spack-stack/tree/feature/gsi-addon).

The error I am getting is during the `configure` step when it tests the C++ compiler using the `-qversion` flag, which does not seem to be a usable flag with Intel 2021.5.0, at least on Orion.  The spack build log is available here: `/work/noaa/global/dhuber/SPACK/spack-stack/envs/gsi-addon/log.install`.  The MET configuration log is available here: `/work/noaa/global/dhuber/SPACK/spack-stack/cache/build_stage/spack-stage-met-9.1.3-sn3cqzpksokdmymuginaxskd7sdktkei/spack-src/config.log`.

Is there a trick I am missing @AlexanderRichert-NOAA?

**Comment by AlexanderRichert-NOAA** [comment] 2023-12-05 16:28
I can't see any of the files under /work/noaa/global/dhuber/SPACK/spack-stack/cache/build_stage/spack-stage-met-9.1.3-gvyd6xfyg6uzygfeg4swz4jqxymr56oi, can you change the permissions?

**Comment by DavidHuber-NOAA** [comment] 2023-12-05 16:39
@AlexanderRichert-NOAA Yes, it's opened up now.  Thanks.

**Comment by AlexanderRichert-NOAA** [comment] 2023-12-05 16:47
Ah yeah I think I've run into this before, it was a 9.1.3-specific problem so I ended up ignoring it. Further down in the config.log, note the `./conftest: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory` (also: not all `$? = 1` cases in config.log necessarily indicate a failure, sometimes it's just a test like for the -qversion flag but it doesn't necessarily cause ./configure to fail, so it's best to look at the most recent instance).

**Comment by AlexanderRichert-NOAA** [comment] 2023-12-05 16:53
Actually I partially take that back-- It looks like it's using paths under your gsi-addon directory structure, not the unified-env one. That's pretty weird, I've never seen spack fail to handle that before. In any case I'll keep digging.

**Comment by AlexanderRichert-NOAA** [comment] 2023-12-05 19:57
Okay, apparently the issue is that python is the wrong dependency type in the met recipe, so the spack rpath scheme isn't working. The fix (which will go into 1.6.0; looks like met is broken in 1.5.1) is to change `depends_on("python@3.6.3:", when="+python", type=("build", "run"))` to `depends_on("python@3.6.3:", when="+python")`

**Comment by DavidHuber-NOAA** [comment] 2023-12-05 20:00
Good to know.  Thanks for the hunting, @AlexanderRichert-NOAA!  I'll make that change locally and continue testing.

**Comment by DavidHuber-NOAA** [comment] 2023-12-07 20:19
That worked, at least mostly.  There was one oddity produced on the `gcc` side, which failed to pickup `hdf5` from `unified-env`, so it and all of the dependent packages (e.g. `netcdf-c`, `netcdf-fortran`, `nco`) were rebuilt under the `gsi-addon` environment, but this seems like a bug elsewhere.  The Intel side only built the requested versions of `bufr/11.7.0`, `met`, and `metplus`.  Otherwise, it appears to have worked correctly.

This template does not include 8-byte integer support for `w3emc` and `ip`.  Do you know if those will be added to the `unified-env` @AlexanderRichert-NOAA?  If not, I can try adding them here.

**Comment by AlexanderRichert-NOAA** [comment] 2023-12-07 22:45
8-byte builds for ip and w3emc are in spack-stack develop, so they'll be in the next release. To tweak them in the existing configuration, just modify common/packages.yaml, or set those variants explicitly in spack.yaml.

**Comment by climbfuji** [comment] 2023-12-19 22:15
We merged the `gsi-addon-dev` template last week. There are still issues with the Python version, but as far as this issue is concerned, it's done.

**Closed as completed by climbfuji** 2023-12-19 22:15 UTC
Labels: NOAA-EMC
