### ISSUE TITLE
Update versions for UFS

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#170] opened 2022-06-02 17:33 UTC
UFS needs MAPL 2.11.0 and ESMF 8.3.0b09.

**Comment by climbfuji** [comment] 2022-06-02 19:26
Duplicate of #102 and #124

**Comment by climbfuji** [comment] 2022-06-03 03:20
Closing because there are already two separate issues for this.

**Closed as not planned** 2022-06-03 03:20 UTC
